### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Apidcloud** [Equals182/eqFTP#105]
Good afternoon

Unfortunately, I've had a bad experience today with eqFTP. Some time ago I was working on a website and had some files locally, but my colleague changed the server ones from his computer. 
Today I established a connection to the server and opened one of the file servers in order to edit it.
After noticing some more modifications had to be done in another file, I opened its LOCAL version and uploaded without noticing, replacing the newest version (from the SERVER).

Conclusion, the server is now using an outdated file causing errors.

Now, I believe this issue can be fixed so it doesn't happen to anyone else in the future. When uploading, the extension could compare the date of the files and in case there's a newer version of the file, ask (popup a warning) the user if he actually wants to replace.

Sincerely,
Apidcloud

**Comment by Equals182** [comment]
Hello

First of all, I'm really sorry to hear that eqFTP somehow passively did a harm to your project. Maybe you should ask your colleague to upload those changes again.

I've already thought about this feature. Since 0.6.0, I believe, there is a feature that allows you to redownload file from server (via right click on local copy).
In version 0.7.0 there's a feature that checks difference between local and remote files while you switching between local files. I mean, when you change current opened file - this new opened file will be immideatly compared with remote copy. (Also there's a 3 seconds pause between file comparison, so don't switch too fast).
Also, in new version (which you can download right now) you can also download remote files and they will be automatically compared with local.
There's still no such thing on upload, but I'll defenitely consider this for future.

Love,
Equals182
<3

**Comment by Apidcloud** [comment]
Thanks for the prompt reply!

Good to know it wasn't a strange request. I'm actually using the version from github (7.0).
The pull request I made earlier was from 7.0 as well.

Sincerely,
Apidcloud

**Comment by Equals182** [comment]
Please, check your connection settings.
Open Connection -> Automatization Tab
Set automatization to Sync (dropdown menu)
Set **Check for differences** on (everything else here set to off, just to check if it works)
Then make some changes in your file, switch from it to another file and back - you should get a notification about difference in files.

**Comment by Apidcloud** [comment]
I didn't know there was such an option!

I'll try it later today :) Thanks again

**Comment by Apidcloud** [comment]
![eqftp](https://cloud.githubusercontent.com/assets/3720818/6470163/8c5af894-c1d9-11e4-94d1-fb94109a91a0.JPG)

I can't do anything when the message shows, and there's that line in queue. By the way, it only shows the messages when I close and open the local file again. Shouldn't it also popup when I right click > Upload ? Or when saving (uploading automatically)

**Comment by Equals182** [comment]
As I already stated:
> There's still no such thing on upload, but I'll defenitely consider this for future.

If you see notification that says that there's a difference - just click on it and wait - it should show you a window with actions you can make.

**Comment by Apidcloud** [comment]
Ah, alright. So you recommend either closing every file or switching between in order to make the comparison. Will do. Thanks

**Comment by Equals182** [comment]
You can just right click on local file and click **redownload** and if files are different - you will see window with actions just like when you click notification.

**Comment by Apidcloud** [comment]
Ok, thanks for the help

**Comment by Equals182** [comment]
I really hope that helps you in future and you'll enjoy using this extension.

**Comment by Apidcloud** [comment]
No worries! I've been using it quite a while and it was the first time I've faced such issue :+1: 
I find it really good.

**Comment by Equals182** [comment]
Thanks!
I'm closing this issue then
