### ISSUE TITLE
v.70 ignore list not working

### ISSUE THREAD

**Issue by nickfmc** [Equals182/eqFTP#131]
No matter what I put in the ignore list it doesn't prevent transfer when Automation set to Sync. I have tried:
*.cfg and also tried specificfilename.cfg and neither do anything I save a .cfg file and it is still uploaded to my server.

**Comment by Equals182** [comment]
I've experienced it too recently. Will work on it when I'll have time.
Thanks for report!

**Comment by Equals182** [comment]
**Short version:**
* Update from `https://github.com/Equals182/eqFTP`
* Add to ignore list 2 lines:
```
**/*.cfg
*.cfg
```
* Try to upload

**Long version:**
Ignore feature works and worked before. BUT! There was another bug in instant update of already existent connections, so when you updated settings in connections, not all of them could work until restart. Now it should work fine.
I understand that `*.cfg` should probably work for every file in every directory, but this is how it is for now.
Please update from repository again and try to add `**/*.cfg` as well. That should work for any `.cfg` files in any directory, because I assume that your file was probably not in root OR your settings wasn't updated at that moment of time.
When file is ignored it will not be added to queue and you won't see any notifications.

Thank you! :)

**Comment by nickfmc** [comment]
Nice! thanks, works now.

**Comment by Equals182** [comment]
Good :)
