### ISSUE TITLE
Check if remote file has been changed

### ISSUE THREAD

**Issue by satur9** [Equals182/eqFTP#163]
Functionality request for a tick box in the "Classic Automization" tab for "Warn if Remote File Changed".

Function would perform a pre-upload check if the file has been amended using a modified date string compare between last download date and remote file modified date, and if remote file modified date is newer, present a popup to user stating that: "The remote file has been modified since last download. Are you sure you wish to overwrite this changed file? | Yes : No".

I am not sure if this is relevant to synchronised projects, but in Classic project where multiple developers may be making changes to the same set of files, this could provide a stop-gap functionality to a full Git type implementation.

**Comment by Rann1** [comment]
This would indeed be an great addition to this plugin!

**Comment by Equals182** [comment]
This functionality is available for Sync version of automatization. The main difference between Classic and Sync is that Sync checks for changes in all of project's files while Classic just triggers upload of current saved file.
Personally, I think Sync is more perspective since it allows to do lot more stuff like auto-uploading CSS file after changing SCSS. Of course it is possible to add features like "Check file for changes" or "Ignore list" to Classic automatization, but is it really necessary and why don't just use Sync?

**Comment by satur9** [comment]
I think between the two features, it really is a matter of scope:
- Sync (from my understanding) targets all files in scope, and you have to explicitly set specific files to be ignored in the config.
- Classic targets only the specific files you have chosen to edit and downloaded in it's scope, and ignores all other files.

Sync it really a Git Lite, working on per-project basis, while Classic is more adhoc for quick changes to certain files only.

Unless of course I have completely misunderstood what Sync mode is, in which case I must apologise and get onboard with using Sync instead.

**Comment by Rann1** [comment]
We chose to use eqFTP because of the Classic reason. We often work in Magento, and... We'll, you don't want to sync all those thousands of files, or even download them before you start working on the project. It's much, much faster if you can just download the select few files you need and get on with it.

**Comment by Equals182** [comment]
Classic is just a really basic realization of Sync. Sync doesn't downloads everything by default.
Main difference between Classic and Sync is the way it uploads files. When you use Classic, uploading starts for currently opened file after you click Save button (or Ctrl+S). When you use Sync uploading starts after file was changed/saved. So Classic listens for Save event and Sync watches for changes in files.
You guys right, Classic is just really simple and straightforward realisation of FTP plugin and Sync is pretty much for kind of deeper integration with project files.
Anyway, I heard you. I'll work on it and I'll try to add this feature for Classic mode.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
