### ISSUE TITLE
Files does not get uploaded

### ISSUE THREAD

**Issue by oleandreasvekve** [Equals182/eqFTP#168]
Hello,

First time I write on github, so please be patient if I write or explain it wrong.

When I save my working documents no files are being uploaded. I have tried using the debug option, and pressing F12, but nothing happens. 

I have the following settings:
Upload File on Save: Even If Disconnected

For remote path I have not written anything as I want everything to be uploaded right into the main root. I have tried changing this to /, but didn't seem to work out.

I can see the files in the eqFTP, so password and settings are correct I believe.

Do you have a working solution for this?

**Comment by satur9** [comment]
Hi oleandreasvekve,

Please can you describe your workflow a bit more?

Are you creating new documents you want to upload, or are you using the eqFTP file browser to open existing files on the remote site?

If these are new files, I believe you need to manually right click them in the folder tree and click "Upload" at least once, in order to create a mapping for eqFTP to the remote site, as eqFTP will not associate *all* local files with remote locations using "Traditional Mode".

If you want to manage projects more efficiently, using automatic synchronization, you should use the newer "Sync" mode under  the Automatization tab.

Personally I only use Traditional mode because I manage exisitng remote files, this works for me as I use the eqFTP remote file browser to open the remote documents, and I never create new documents, so it really depends on your overall workflow and expectations.

**Comment by oleandreasvekve** [comment]
Thank you. The issue was that I was using Brackets and the extension on the wrong way.

I opened the files from my computer into brackets, and not downloading the files from the server. When I downloaded the files from the server directly into Brackets it works. Thanks :)

**Comment by Equals182** [comment]
Thank you @satur9 for help! Really appreciate it! :+1: 
@oleandreasvekve feel free to ask anything here, it's totally fine with me :) Hope you won't have any troubles using this ext.
