### ISSUE TITLE
Unable to view remote files using / as remote path

### ISSUE THREAD

**Issue by newelement** [Equals182/eqFTP#202]
On WPEngine the SFTP account puts you in the root folder you have access to therefore there's not really a remote path. When using / as the remote path value I get the notification that eqFTP cannot use that directory.

**Comment by Equals182** [comment]
`remote path` setting sets default folder to open via eqFTP and use it like root folder - all paths in eqFTP will be relative to this. Also none of folders outside this one will be shown or usable.
If you want to use some directory that way, and you can't use `/` symbol at beginning, try setting `remote path` setting without it.
For example in your default root folder there's a folder called `foo`, and you want to make it root for eqFTP - set `remote path` to `foo` and that should do the work.
Using `/foo` makes eqFTP think that you literally want to have default access to folder `foo` in root directory on server, which might be impossible due to restrictions of your server.
If you already tried this and you still can't have it as default folder, please send me logs ([here's how to do it](http://equals182.github.io/eqFTP/#creating-issue)). Please don't forget to remove any private information (like passwords and stuff).

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
