### ISSUE TITLE
Open Local Folder Automatically

### ISSUE THREAD

**Issue by topwebs** [Equals182/eqFTP#260]
## Expected Behavior

I don't see a toggle to automatically open the local folder when the ftp folder is opened. Not sure if this is supposed to happen automatically or it is a feature not yet implemented.

**Comment by Equals182** [comment]
This one is not implemented yet, but we will add it soon
Thanks!

**Comment by topwebs** [comment]
Very nice interface and seems to work very smoothly. Great job on the new version!

**Comment by Equals182** [comment]
Thank you! We're trying our best to make eqFTP better 👍 
Hope you won't have any major issues, but if anything, I'm here to solve them :)

**Comment by BarryEgan** [comment]
I don't have a previous settings file, so I'm trying to create one, clicking create and saving as settings.eqftp, but nothing happens. then I click locate and select the new setting file but still no progress. :/

**Comment by Equals182** [comment]
Hey! I've added this feature and tested it couple of times, looking good for me. Just like date format it should work immediately after settings file has been saved.
Please, update eqFTP and check it out yourself :) This one will require extra Node reload due to changes in ftpDomain.js.

Just in case:
- Open **Extension Manager** and click **Install from URL**
- Put `https://github.com/Equals182/eqFTP` in there
- After Brackets restarted click Debug -> Restart Node in Brackets' Menu bar
- Press F5 in couple of seconds after that

**Comment by topwebs** [comment]
Works well, thanks.

**Comment by Equals182** [comment]
I just thought, would it be better to give this setting to every connection instead of global? What do you think?

**Comment by topwebs** [comment]
I prefer global, rather than having to click another option for every new connection. I really don't see why anyone would not want to open the local folder when they connect. I assume that if there is no local folder specified, then nothing happens.

**Comment by Equals182** [comment]
Yeah, too many options would probably overload connection's settings page and that's bad, of course. Thanks :)
